services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    expose:
      - 8080
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    env_file: .env
    image: nginx:alpine
    volumes:
      - ./nginx.conf.template/:/etc/nginx/templates/default.conf.template
    ports:
      - '80:80'
    depends_on:
      - open-webui

volumes:
  open-webui:
